"""Finite positive witnesses give a continuous parametric decay lower bound.

No eigenvalue estimates are accepted. A witness can be generated by any method;
the lower bound uses the actual sparse operator product and its positive vector.
This is a research certificate primitive, not a response-space construction.
"""
import numpy as np
import scipy.sparse as sp


class AffineDecay:
    def __init__(self, K, C, H, fallback):
        self.K, self.c, self.H = K, C.diagonal(), H
        self.fallback = float(fallback)
        diagonals = []
        for A in H:
            diagonal = A.diagonal()
            if (A-sp.diags(diagonal)).nnz or np.any(diagonal < 0):
                raise ValueError('diagonal nonnegative Robin operators required')
            diagonals.append(diagonal/self.c)
        coefficients = np.asarray(diagonals)
        self.active = np.any(coefficients != 0, axis=0)
        self.coefficients = coefficients[:, self.active]
        self.intercepts, self.interior, self.vectors, self.anchors = [], [], [], []

    def add(self, z, h):
        z = np.asarray(z)
        if np.any(z <= 0) or not np.all(np.isfinite(z)):
            raise ValueError('finite strictly positive witness required')
        z = z/np.max(z)
        intercept = (self.K@z)/(self.c*z)
        self.intercepts.append(intercept[self.active])
        self.interior.append(float(np.min(intercept[~self.active]))
                             if np.any(~self.active) else float('inf'))
        self.vectors.append(z)
        self.anchors.append(np.asarray(h).copy())

    def __call__(self, h):
        if not self.intercepts:
            return self.fallback
        boundary = np.asarray(self.intercepts)+np.asarray(h)@self.coefficients
        lower = np.minimum(np.asarray(self.interior), np.min(boundary, axis=1))
        return float(max(self.fallback, np.max(lower)))
