"""Modified incomplete LDL lower operator for a grounded bipartite graph.

Every fill edge generated by elimination is absent from the bipartite original
pattern. Dropping that COMPLETE Laplacian edge lowers the exact Schur complement.
Induction therefore yields A_min >= Z^{-1} L diag(pivots) L.T Z^{-1} > 0.
The sparse triangular sweeps are measured as full-size auxiliary applications.
"""
import time
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as sla
from graph_inverse_lower import GraphInverseLower


class BipartiteInverseLower(GraphInverseLower):
    def __init__(self,A,z,colors):
        start=time.perf_counter()
        z=np.asarray(z);z=z/np.max(z);colors=np.asarray(colors)
        if np.any(z<=0) or np.any(A@z<=0):
            raise ValueError('strictly positive grounded scaling required')
        Z=sp.diags(z);S=(Z@A@Z).tocsr();U=sp.triu(S,k=1,format='csr')
        parents=np.repeat(np.arange(len(z)),np.diff(U.indptr))
        if np.any(U.data>0) or np.any(colors[parents]==colors[U.indices]):
            raise ValueError('bipartite nonpositive off-diagonal graph required')
        pivots=S.diagonal().copy()
        for i in range(len(z)):
            if pivots[i]<=0:
                raise ValueError('nonpositive modified LDL pivot')
            start_i,end_i=U.indptr[i:i+2]
            rows=U.indices[start_i:end_i];values=U.data[start_i:end_i]
            pivots[rows]-=values*values.sum()/pivots[i]
        lower=sp.coo_matrix((U.data/pivots[parents],(U.indices,parents)),shape=S.shape)
        self.L=(sp.eye(len(z),format='csr')+lower).tocsr()
        self.z,self.pivots=z,pivots
        self.robin=None
        self.statistics=dict(kind='bipartite_modified_ldl',lower_nonzeros=self.L.nnz,
            factor_seconds=time.perf_counter()-start,whiten_calls=0,
            whiten_rhs_columns=0,whiten_seconds=0.)

    def whiten(self,R):
        start=time.perf_counter()
        Y=sla.spsolve_triangular(self.L,self.z[:,None]*R,lower=True,unit_diagonal=True)
        Y/=np.sqrt(self.pivots)[:,None]
        self.statistics['whiten_calls']+=1
        self.statistics['whiten_rhs_columns']+=R.shape[1]
        self.statistics['whiten_seconds']+=time.perf_counter()-start
        return Y
