"""Finite-interval Zolotarev samples for positive-definite resolvent families.

For ``A(h) = A0 + h H`` with finite generalized spectrum
``spectrum(A0, H) subset [alpha, beta]``, the scalar kernel is
``1 / (lambda + h)``.  The samples returned here minimize the Zolotarev
separation ratio between ``[alpha, beta]`` and
``[-h_max, -h_min]``.  Consequently, the snapshot space generated by
``A(h_j)^{-1} b`` contains a rational interpolant whose uniform relative
resolvent error is bounded by :attr:`ZolotarevRule.error_bound`.

The construction uses the resolvent skeleton identity and the Möbius-mapped
third Zolotarev problem described by Massei and Robol, "Rational Krylov for
Stieltjes Matrix Functions: Convergence and Pole Selection" (2020).  SciPy
uses the elliptic parameter ``m = k**2`` rather than the elliptic modulus ``k``.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import time

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
from scipy import special


@dataclass(frozen=True)
class ZolotarevRule:
    """One finite-interval minimax rational interpolation rule."""

    parameter_nodes: np.ndarray
    spectral_nodes: np.ndarray
    cross_ratio: float
    error_bound: float


@dataclass(frozen=True)
class CoordinateSpectrum:
    """Numerical enclosure of one coordinate's finite generalized spectrum."""

    lower: float
    upper: float
    active_cells: int
    lower_ritz_residual: float
    upper_ritz_residual: float
    seconds: float


def _positive_interval(interval, name: str) -> tuple[float, float]:
    values = np.asarray(interval, dtype=np.float64).ravel()
    if values.size != 2:
        raise ValueError(f"{name} must contain exactly two endpoints")
    low, high = float(values[0]), float(values[1])
    if not (math.isfinite(low) and math.isfinite(high) and 0.0 < low < high):
        raise ValueError(f"{name} must satisfy 0 < low < high")
    return low, high


def _mobius_map(source: np.ndarray, target: np.ndarray):
    """Return the real Möbius map taking four compatible points to four points."""
    matrix = np.column_stack(
        (source, np.ones(4), -target * source, -target)
    )
    _u, singular_values, vh = np.linalg.svd(matrix)
    coefficients = vh[-1, :]
    a, b, c, d = coefficients

    def transform(z):
        z = np.asarray(z, dtype=np.float64)
        return (a * z + b) / (c * z + d)

    mapped = transform(source)
    scale = max(1.0, float(np.max(np.abs(target))))
    if float(np.max(np.abs(mapped - target))) > 1.0e-9 * scale:
        raise RuntimeError(
            "failed to construct the two-interval Möbius transform; "
            f"smallest singular value={singular_values[-1]:.3e}"
        )
    return transform


def zolotarev_rule(
    spectral_interval,
    parameter_interval,
    count: int,
) -> ZolotarevRule:
    """Return the degree-``count`` finite-interval Zolotarev sampling rule.

    ``parameter_nodes`` are the positive values at which full responses are
    sampled.  ``spectral_nodes`` are only needed to form the corresponding
    skeleton interpolant; constructing a Galerkin snapshot space does not need
    them.
    """
    alpha, beta = _positive_interval(spectral_interval, "spectral_interval")
    h_min, h_max = _positive_interval(parameter_interval, "parameter_interval")
    if int(count) != count or count < 1:
        raise ValueError("count must be a positive integer")
    count = int(count)

    # Ordered intervals [a,b] < [c,d].  The classical Zolotarev function has
    # zeros on [a,b] and poles on [c,d].  Its reciprocal therefore has poles
    # -h_j on the negative interval and zeros on the positive spectral one,
    # exactly matching the resolvent skeleton error.
    a, b, c, d = -h_max, -h_min, alpha, beta
    cross_ratio = ((c - a) * (d - b)) / ((c - b) * (d - a))
    tau = -1.0 + 2.0 * cross_ratio + 2.0 * math.sqrt(
        cross_ratio * cross_ratio - cross_ratio
    )
    elliptic_parameter = 1.0 - 1.0 / (tau * tau)
    complete_integral = special.ellipk(elliptic_parameter)

    transform = _mobius_map(
        np.asarray([-1.0, -1.0 / tau, 1.0 / tau, 1.0]),
        np.asarray([a, b, c, d]),
    )
    arguments = (
        (2.0 * np.arange(1, count + 1) - 1.0)
        * complete_integral
        / (2.0 * count)
    )
    _sn, _cn, dn, _phase = special.ellipj(arguments, elliptic_parameter)
    negative_nodes = transform(-dn)
    positive_nodes = transform(dn)

    parameter_nodes = np.sort(-np.asarray(negative_nodes, dtype=np.float64))
    spectral_nodes = np.sort(np.asarray(positive_nodes, dtype=np.float64))
    error_bound = 4.0 * math.exp(
        -count * math.pi * math.pi / math.log(16.0 * cross_ratio)
    )
    return ZolotarevRule(
        parameter_nodes=parameter_nodes,
        spectral_nodes=spectral_nodes,
        cross_ratio=float(cross_ratio),
        error_bound=float(error_bound),
    )


def zolotarev_count(
    spectral_interval,
    parameter_interval,
    tolerance: float,
    *,
    maximum: int = 512,
) -> int:
    """Smallest degree satisfying the closed-form Zolotarev error bound."""
    if not (math.isfinite(tolerance) and 0.0 < tolerance < 1.0):
        raise ValueError("tolerance must satisfy 0 < tolerance < 1")
    for count in range(1, maximum + 1):
        if (
            zolotarev_rule(spectral_interval, parameter_interval, count).error_bound
            <= tolerance
        ):
            return count
    raise RuntimeError(
        f"Zolotarev count did not reach tolerance {tolerance:g} by {maximum}"
    )


def coordinate_spectral_enclosures(
    base_operator,
    boundary_terms,
    parameter_ranges,
    *,
    eigensolver_tolerance: float = 1.0e-10,
    safety_factor: float = 1.0e-8,
) -> list[CoordinateSpectrum]:
    """Estimate box-wide finite generalized spectra for every HTC coordinate.

    For coordinate ``i`` and fixed remaining parameters, eliminate all cells on
    which ``H_i`` vanishes.  The finite generalized eigenvalues are those of
    the boundary Schur complement relative to the positive diagonal of
    ``H_i``.  Loewner monotonicity puts the smallest value at the lower corner
    of all other parameters and the largest value at their upper corner.

    The lower endpoint is obtained from the largest eigenvalue of
    ``H_i**(1/2) A_minus**(-1) H_i**(1/2)`` using one sparse factorization and
    Lanczos iterations.  For the upper endpoint, the active principal block is
    a rigorous Schur-complement upper bound; a generalized largest-eigenvalue
    solve avoids forming the Schur complement.  ``safety_factor`` expands both
    numerical Ritz estimates outwards.  The mathematical enclosure is exact
    apart from the iterative eigensolver convergence, whose residuals are
    reported in the result.
    """
    K = sp.csc_matrix(base_operator)
    terms = [sp.csc_matrix(term) for term in boundary_terms]
    ranges = np.asarray(parameter_ranges, dtype=np.float64)
    if ranges.shape != (len(terms), 2):
        raise ValueError("parameter_ranges must have shape (n_terms, 2)")
    if len(terms) < 2:
        raise ValueError(
            "coordinate_spectral_enclosures requires another positive boundary "
            "group to make A_minus coercive"
        )

    results: list[CoordinateSpectrum] = []
    for coordinate, term in enumerate(terms):
        started = time.perf_counter()
        diagonal = np.asarray(term.diagonal(), dtype=np.float64).ravel()
        active = np.flatnonzero(diagonal > 0.0)
        if not active.size:
            raise ValueError(f"boundary term {coordinate} has no positive entries")
        square_root = np.sqrt(diagonal[active])

        lower_corner = K.copy()
        upper_corner = K.copy()
        for other, other_term in enumerate(terms):
            if other == coordinate:
                continue
            lower_corner = lower_corner + ranges[other, 0] * other_term
            upper_corner = upper_corner + ranges[other, 1] * other_term

        factor = spla.splu(lower_corner.tocsc())
        full_size = K.shape[0]

        def inverse_action(vector):
            rhs = np.zeros(full_size, dtype=np.float64)
            rhs[active] = square_root * np.asarray(vector, dtype=np.float64)
            solved = factor.solve(rhs)
            return square_root * solved[active]

        inverse_boundary = spla.LinearOperator(
            (active.size, active.size),
            matvec=inverse_action,
            rmatvec=inverse_action,
            dtype=np.float64,
        )
        theta, theta_vector = spla.eigsh(
            inverse_boundary,
            k=1,
            which="LA",
            tol=eigensolver_tolerance,
        )
        theta_value = float(theta[0])
        theta_residual = float(
            np.linalg.norm(
                inverse_action(theta_vector[:, 0])
                - theta_value * theta_vector[:, 0]
            )
        )
        lower = 1.0 / (theta_value * (1.0 + safety_factor))

        principal = upper_corner[active, :][:, active].tocsc()
        weight = sp.diags(diagonal[active], format="csc")
        upper_value, upper_vector = spla.eigsh(
            principal,
            M=weight,
            k=1,
            which="LA",
            tol=eigensolver_tolerance,
        )
        upper_value = float(upper_value[0])
        vector = upper_vector[:, 0]
        upper_residual = float(
            np.linalg.norm(principal @ vector - upper_value * (weight @ vector))
        )
        upper = upper_value * (1.0 + safety_factor)

        results.append(
            CoordinateSpectrum(
                lower=float(lower),
                upper=float(upper),
                active_cells=int(active.size),
                lower_ritz_residual=theta_residual,
                upper_ritz_residual=upper_residual,
                seconds=time.perf_counter() - started,
            )
        )
    return results
