% rom_parameters.m generated by FT ROM extraction
% time range
in.tscan = [0, 1.00000e+03];
% solution control
 in.ode_reltol = 1.0e-7;
 in.ode_abstol = 1.0e-5;
% htcs - number should match ROM
 in.h = [ 1, 1.00000e+03        % Ambient:1
          2, 5.00000e+01 ];     % Ambient:0
 in.Tamb = [ 1, 3.50000e+01        % Ambient:1
          2, 3.50000e+01 ];     % Ambient:0
% set the required uniform Tinit
in.Tinitial = 3.50000e+01;
% htcs names
 in.h_name = [ "Ambient:1"    % htc range 1.00000e+00 1.00000e+04
               "Ambient:0" ]; % htc range 1.00000e+00 1.00000e+04
 % sources... 
% source name: S0
 in.source{1}.name = "S0";
 in.source{1}.steps_type = 'constant';
 in.source{1}.val = 1.00000e-01;
% source name: S1
 in.source{2}.name = "S1";
 in.source{2}.steps_type = 'constant';
 in.source{2}.val = 2.00000e-01;
% source name: S2
 in.source{3}.name = "S2";
 in.source{3}.steps_type = 'constant';
 in.source{3}.val = 3.00001e-01;
% source name: S3
 in.source{4}.name = "S3";
 in.source{4}.steps_type = 'constant';
 in.source{4}.val = 4.00001e-01;
 % COG source probes... 
in.probe{1}.name = "S0";
in.probe{2}.name = "S1";
in.probe{3}.name = "S2";
in.probe{4}.name = "S3";
 % user set probes ... 
 % other example options for sources:
 % Either:
 %{
     in.source{1}.steps_type = 'piecewise-linear';
     in.source{1}.times = [ 0 ;
                            10;
                            20 ].';
     in.source{1}.steps = [ 10 ;
                            20;
                            20 ].';
 %}
 % Or:
 %{
     in.source{1}.steps_type = 'sinusoidal';
     in.source{1}.step = 5.0; 
     in.source{1}.amplitude = 2.0; 
     in.source{1}.time = 3.0; 
     in.source{1}.period = 5.0; 
 %}
 % Or:
 %{
     in.source{1}.steps_type = 'pulse-function';
     in.source{1}.step = 5.0; 
     in.source{1}.amplitude = 2.0; 
     in.source{1}.rise_time = 2.0; 
     in.source{1}.high_time = 25.0; 
     in.source{1}.fall_time = 2.0; 
     in.source{1}.time = 3.0; 
     in.source{1}.period = 50.0; 
 %}
 % Or:
 %{
     in.source{1}.steps_type = 'step-on';
     in.source{1}.valoff = 0.0; 
     in.source{1}.valon = 2.0; 
     in.source{1}.timeon = 20.0; 
 %}
 % Or:
 %{
     in.source{1}.steps_type = 'step-off;
     in.source{1}.valoff = 0.0; 
     in.source{1}.valon = 2.0; 
     in.source{1}.timeoff = 20.0; 
 %}
% end of file