simulation_type = "transient"
time = 0.01
timestep = 0.01
sampling_intvl = 0.01
proc_freq = 3000000000.0
ambient = 318.15
init_temperature = 318.15
mesh_file_path = "mesh.msh"
ptrace_file_path = "gcc.ptrace"
[[stackup]]
tag = 1
name = "layer_1"
thickness = 0.00015
material = "silicon"
active = true
flp_file = "ev6.flp"
lx = 0.0
ly = 0.0
dx = 0.016
dy = 0.016

[[stackup]]
tag = 1000
name = "TIM"
thickness = 2e-5
material = "tim"
active = false
lx = 0.0
ly = 0.0
dx = 0.016
dy = 0.016

[[stackup]]
tag = 1001
name = "Spreader"
thickness = 0.001
material = "aluminum"
active = false
lx = -0.006999999999999999
ly = -0.006999999999999999
dx = 0.03
dy = 0.03

[[stackup]]
tag = 1002
name = "Sink"
thickness = 0.0069
material = "aluminum"
active = false
lx = -0.022
ly = -0.022
dx = 0.06
dy = 0.06

[[boundary_conditions]]
name = "sink_conv"
type = "convection"
h = 2777.777777777778
T_inf = 318.15
selection = [ 2032,]

[materials.silicon]
k = 130.0
cp = 1630300.0
fluid = false

[materials.water]
k = 0.6069
cp = 4172638.0
fluid = true
dynamic_viscosity = 0.000889

[materials.aluminum]
k = 237.0
cp = 2422000.0
fluid = false

[materials.copper]
k = 400.0
cp = 3440000.0
fluid = false

[materials.tim]
k = 4.0
cp = 4000000.0
fluid = false
